package tracinglangfusetest
package main

import (















































































































}	fmt.Println("  - LLM generation details (input, output, token usage)")	fmt.Println("  - Tool outputs (generated palette)")	fmt.Println("  - Tool inputs (primary_color, palette_size)")	fmt.Println("Check your Langfuse dashboard to see:")	fmt.Println("\n✅ Trace sent to Langfuse!")	time.Sleep(2 * time.Second)	// Wait a moment for traces to be sent	}		log.Printf("Warning: failed to flush traces: %v", err)	if err := tracer.Flush(context.Background()); err != nil {	fmt.Println("\nFlushing traces to Langfuse...")	// Flush traces	fmt.Printf("\nAgent Response:\n%s\n", result)	}		log.Fatalf("Agent run failed: %v", err)	if err != nil {	result, err := agent.Run(ctx, "Generate a color palette based on the color red (#FF0000)")	fmt.Println("Running agent with Langfuse tracing...")	// Run the agent	defer endTrace()	)		}),			"query": "Generate a color palette based on red",		agentkit.WithTraceInput(map[string]any{		agentkit.WithSessionID("test-session"),		agentkit.WithUserID("test-user"),	ctx, endTrace := tracer.StartTrace(ctx, "palette-generation-test",	ctx := context.Background()	// Create a trace context	}		log.Fatalf("Failed to create agent: %v", err)	if err != nil {	})		Tools:  []agentkit.Tool{generatePalette},		Tracer: tracer,		Model:  "gpt-4o-mini",		APIKey: os.Getenv("OPENAI_API_KEY"),	agent, err := agentkit.New(agentkit.Config{	// Create agent with tracer	}		},			return palette, nil			}				}[:paletteSize],					"#FF33F5",					"#3357FF",					"#33FF57",					"#FF5733",					primaryColor,				"colors": []string{				"primary": primaryColor,			palette := map[string]any{			// Simulate palette generation			}				paletteSize = int(size)			if size, ok := args["palette_size"].(float64); ok {			paletteSize := 5			primaryColor := args["primary_color"].(string)		Handler: func(ctx context.Context, args map[string]any) (any, error) {		},			"required": []string{"primary_color"},			},				},					"description": "Number of colors in the palette",					"type":        "integer",				"palette_size": map[string]any{				},					"description": "The primary color in hex format (e.g., #FF0000)",					"type":        "string",				"primary_color": map[string]any{			"properties": map[string]any{			"type": "object",		Parameters: map[string]any{		Description: "Generates a color palette based on a primary color",		Name:        "generate_palette",	generatePalette := agentkit.Tool{	// Create test tool	defer tracer.Shutdown(context.Background())	}		log.Fatalf("Failed to create Langfuse tracer: %v", err)	if err != nil {	})		Enabled:     true,		ServiceName: "agentkit-tracing-test",		BaseURL:     "https://cloud.langfuse.com",		SecretKey:   os.Getenv("LANGFUSE_SECRET_KEY"),		PublicKey:   os.Getenv("LANGFUSE_PUBLIC_KEY"),	tracer, err := agentkit.NewLangfuseTracer(agentkit.LangfuseConfig{	// Initialize Langfuse tracerfunc main() {// Demonstration of the Langfuse tracing fix)	"github.com/darkostanimirovic/agentkit"	"time"	"os"	"log"	"fmt"	"context"